In [1]:
# Basic variables and data types
a = 10
b = 3.14
name = "PyTorch Learner"
is_active = True

# Simple print
print(f"Hello, {name}! Let's learn PyTorch.")

# List and loops
for i in range(5):
    print(i, end=' ')


Hello, PyTorch Learner! Let's learn PyTorch.
0 1 2 3 4 

In [13]:
import torch
import numpy as np

# Create tensors
x = torch.tensor([1, 2, 3])
print("Tensor x:", x)

#from numpy array
data = [[1, 2],[3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#from another tensor
x_ones = torch.ones_like(x_np) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

#with random value
shape = (2,3)
rand_tensor = torch.rand(shape)
print(f"Random Tensor: \n {rand_tensor} \n")


Tensor x: tensor([1, 2, 3])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3552, 0.5426, 0.1072],
        [0.9432, 0.2765, 0.0988]]) 



In [14]:
#attributes
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
# Tensor with gradient tracking
a = torch.tensor([2.0, 3.0], requires_grad=True)
b = a * 2
print("b:", b)
b.sum().backward()  # compute gradients
print("Gradient of a:", a.grad)

b: tensor([4., 6.], grad_fn=<MulBackward0>)
Gradient of a: tensor([2., 2.])


In [16]:
#indexing and slicing 
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print("Full tensor:\n", x)

print("Access row 0:", x[0])
print("Access element [2,1]:", x[2,1])

print("Slice rows 0-1, columns 1-2:\n", x[0:2, 1:3])


Full tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Access row 0: tensor([1, 2, 3])
Access element [2,1]: tensor(8)
Slice rows 0-1, columns 1-2:
 tensor([[2, 3],
        [5, 6]])


In [23]:
#reshaping
x = torch.arange(1, 13)
print("Original tensor:", x)

x_reshaped = x.view(3, 4)  # reshape to 3 rows, 4 columns
print("Reshaped tensor:\n", x_reshaped)

x_flattened = x_reshaped.view(-1)  # flatten to 1D
print("Flattened tensor:", x_flattened)


Original tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Reshaped tensor:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Flattened tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [24]:
a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Matrix multiplication:", torch.matmul(a.view(1, 2), b.view(2, 1)))


Addition: tensor([4., 6.])
Multiplication: tensor([3., 8.])
Matrix multiplication: tensor([[11.]])


In [27]:
#Exercise to do-Try creating a tensor representing a 4x4 identity matrix using PyTorch function torch.eye

y=torch.eye(4)
print(x)
print(y)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
